/**
 * Rebuilds screens/body-content.html, src/styles.css, and src/catalog.js
 * from index.original.html. Regenerates src/app.js (shell loader + /detail?id= routing).
 * Do not hand-edit src/app.js — re-run this tool.
 * `--from-original` is accepted and is now the default (same behavior).
 */
const fs = require('fs').promises;
const path = require('path');

const BODY_BLOCK_IDS = [
  'app-splash',
  'home',
  'admin-drawer',
  'detail',
  'create-screen',
  'lightbox',
  'toast',
  'sticky-notice',
  'map-sheet',
];

function extractBalancedDivById(html, id) {
  const esc = id.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const re = new RegExp(`<div\\b[^>]*\\bid=["']${esc}["'][^>]*>`, 'i');
  const m = html.match(re);
  if (!m || m.index === undefined) {
    throw new Error(`extract-shell: could not find opening <div id="${id}">`);
  }
  const start = m.index;
  let i = html.indexOf('>', start) + 1;
  let depth = 1;
  while (i < html.length && depth > 0) {
    const nextOpen = html.indexOf('<div', i);
    const nextClose = html.indexOf('</div>', i);
    if (nextClose === -1) {
      throw new Error(`extract-shell: unclosed <div id="${id}">`);
    }
    if (nextOpen !== -1 && nextOpen < nextClose) {
      depth += 1;
      i = nextOpen + 4;
    } else {
      depth -= 1;
      i = nextClose + 6;
    }
  }
  return html.slice(start, i);
}

function sliceBodyBeforeScripts(html) {
  const bodyMatch = html.match(/<body\b[^>]*>([\s\S]*?)<\/body>/i);
  if (!bodyMatch) throw new Error('extract-shell: no <body> in source');
  const inner = bodyMatch[1];
  const cut = inner.search(/<script\b/i);
  return cut === -1 ? inner : inner.slice(0, cut);
}

function collectInlineScripts(html) {
  const inlineScriptRegex = /<script\b([^>]*)>([\s\S]*?)<\/script>/gi;
  let appScripts = '';
  let m;
  while ((m = inlineScriptRegex.exec(html)) !== null) {
    const attrs = m[1] || '';
    if (!/\bsrc\b\s*=/.test(attrs)) {
      appScripts += m[2] + '\n';
    }
  }
  return appScripts;
}

function collectInlineStyles(html) {
  const styleRegex = /<style\b[^>]*>([\s\S]*?)<\/style>/gi;
  let styles = '';
  let m;
  while ((m = styleRegex.exec(html)) !== null) {
    styles += m[1] + '\n';
  }
  return styles;
}

async function run() {
  const root = process.cwd();
  const originalPath = path.join(root, 'index.original.html');
  let html;
  try {
    html = await fs.readFile(originalPath, 'utf8');
  } catch (e) {
    console.error('Read index.original.html failed:', e.message);
    process.exit(1);
  }

  const bodyOnly = sliceBodyBeforeScripts(html);
  const parts = BODY_BLOCK_IDS.map((id) => extractBalancedDivById(bodyOnly, id));
  const bodyContent = `${parts.join('\n\n')}\n`;

  const screensDir = path.join(root, 'screens');
  await fs.mkdir(screensDir, { recursive: true });

  // Remove stale fragment files from the broken regex split (optional cleanup)
  try {
    const entries = await fs.readdir(screensDir);
    await Promise.all(
      entries
        .filter((f) => f.endsWith('.html'))
        .map((f) => fs.unlink(path.join(screensDir, f)).catch(() => {}))
    );
  } catch (_) {}

  const bodyPath = path.join(screensDir, 'body-content.html');
  await fs.writeFile(bodyPath, bodyContent, 'utf8');
  console.log('Wrote', path.relative(root, bodyPath));

  const srcDir = path.join(root, 'src');
  await fs.mkdir(srcDir, { recursive: true });
  const stylesText = collectInlineStyles(html);
  const stylesPath = path.join(srcDir, 'styles.css');
  if (stylesText.trim()) {
    await fs.writeFile(stylesPath, `/* extracted from index.original.html */\n${stylesText}`, 'utf8');
    console.log('Wrote', path.relative(root, stylesPath));
  } else {
    console.warn('No <style> blocks found in index.original.html; left styles.css unchanged.');
  }

  const appScripts = collectInlineScripts(html);
  const catalogPath = path.join(srcDir, 'catalog.js');
  await fs.writeFile(catalogPath, appScripts, 'utf8');
  console.log('Wrote', path.relative(root, catalogPath), '(from index.original.html)');

  const appJsContent = `// Generated by tools/extract-shell.js — do not hand-edit; re-run the tool.
const ROOT = document.getElementById('app-root');

async function fetchFragment(url) {
  const res = await fetch(url, { cache: 'no-store' });
  if (!res.ok) throw new Error('Failed to fetch ' + url);
  return await res.text();
}

let shellReadyPromise = null;

function loadShellDom() {
  return fetchFragment('/screens/body-content.html').then((html) => {
    ROOT.innerHTML = html;
  });
}

function loadCatalog() {
  if (window.__eventcataCatalogLoaded) {
    return window.__eventcataCatalogScript || Promise.resolve();
  }
  window.__eventcataCatalogLoaded = true;
  window.__eventcataCatalogScript = new Promise((resolve, reject) => {
    const el = document.createElement('script');
    el.src = '/src/catalog.js?v=11';
    el.async = false;
    el.onload = () => resolve();
    el.onerror = () => reject(new Error('Failed to load catalog.js'));
    document.body.appendChild(el);
  });
  return window.__eventcataCatalogScript;
}

function ensureShell() {
  if (!shellReadyPromise) {
    shellReadyPromise = loadShellDom()
      .catch((e) => {
        console.warn('Shell fetch failed', e);
        return fetchFragment('/offline.html').then((h) => {
          ROOT.innerHTML = h;
        });
      })
      .then(() => loadCatalog())
      .catch((e) => {
        console.warn('Catalog load failed', e);
      });
  }
  return shellReadyPromise;
}

function pathToScreenId(pathname) {
  const p = pathname || '/';
  if (p === '/detail' || p === '/detail/') return 'detail';
  if (p === '/create' || p === '/create/') return 'create-screen';
  return 'home';
}

function applyPathToUi(pathname) {
  const path = pathname || '/';
  const params = new URLSearchParams(window.location.search);
  try {
    const eventMatch = path.match(/^\\/e\\/([^/]+)\\/?$/);
    if (eventMatch && typeof window.openDetail === 'function') {
      window.openDetail(decodeURIComponent(eventMatch[1]));
      return;
    }
    if (path === '/detail' || path.startsWith('/detail')) {
      const eventId = params.get('id');
      if (eventId && typeof window.openDetail === 'function') {
        window.openDetail(eventId);
        return;
      }
      if (typeof window.navigate === 'function') window.navigate('home');
      return;
    }
    if ((path === '/create' || path === '/create/') && typeof window.openCreate === 'function') {
      window.openCreate();
      return;
    }
    const id = pathToScreenId(path);
    if (typeof window.navigate === 'function') window.navigate(id);
  } catch (e) {
    console.warn('applyPathToUi', e);
  }
}

async function navigatePath(pathname) {
  await ensureShell();
  applyPathToUi(pathname);
  window.scrollTo(0, 0);
  if (window.__screenShown) {
    try {
      window.__screenShown(pathname || '/');
    } catch (e) {}
  }
}

document.addEventListener('click', (e) => {
  const a = e.target.closest('a[data-nav]');
  if (!a) return;
  e.preventDefault();
  const href = a.getAttribute('href') || '/';
  history.pushState({}, '', href);
  void navigatePath(href);
});

window.addEventListener('popstate', () => {
  void navigatePath(location.pathname);
});

window.addEventListener('load', () => {
  void navigatePath(location.pathname || '/');
});
`;

  const appJsPath = path.join(srcDir, 'app.js');
  await fs.writeFile(appJsPath, appJsContent, 'utf8');
  console.log('Wrote', path.relative(root, appJsPath));
  console.log('Done. body-content.html, styles.css, catalog.js, and app.js match index.original.html.');
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
