/**
 * @deprecated This script used a naive regex and truncated nested <div> trees.
 * Use `node tools/extract-shell.js` (reads index.original.html) to rebuild the shell.
 */
const fs = require('fs').promises;
const path = require('path');

async function ensureDir(dir) {
  try { await fs.mkdir(dir, { recursive: true }); } catch (e) {}
}

async function run() {
  const root = process.cwd();
  const idxPath = path.join(root, 'index.html');
  const backupPath = path.join(root, 'index.original.html');

  let html;
  try {
    html = await fs.readFile(idxPath, 'utf8');
  } catch (e) {
    console.error('index.html not found in', root);
    process.exit(1);
  }

  // Backup original
  await fs.writeFile(backupPath, html, 'utf8');
  console.log('Backup written to index.original.html');

  // Extract title
  const titleMatch = html.match(/<title[^>]*>([\s\S]*?)<\/title>/i);
  const title = titleMatch ? titleMatch[1].trim() : 'EventCata by Ugoo Okogeri';

  // Extract <style> content
  const styleRegex = /<style\b[^>]*>([\s\S]*?)<\/style>/gi;
  let styles = '';
  let m;
  while ((m = styleRegex.exec(html)) !== null) {
    styles += m[1] + '\n';
  }

  // Extract external script src attributes
  const externalScripts = [];
  const extScriptRegex = /<script\b[^>]*\bsrc\s*=\s*["']([^"']+)["'][^>]*><\/script>/gi;
  while ((m = extScriptRegex.exec(html)) !== null) {
    externalScripts.push(m[1]);
  }

  // Extract inline scripts (scripts without a src attribute)
  const inlineScriptRegex = /<script\b([^>]*)>([\s\S]*?)<\/script>/gi;
  let appScripts = '';
  while ((m = inlineScriptRegex.exec(html)) !== null) {
    const attrs = m[1] || '';
    if (!/\bsrc\b\s*=/.test(attrs)) {
      appScripts += m[2] + '\n';
    }
  }

  // Extract screen-like fragments: <section id="..."> and other common top-level id'ed elements
  const fragmentDir = path.join(root, 'screens');
  await ensureDir(fragmentDir);

  const fragmentMatches = [];
  const sectionRegex = /<section\b[^>]*\bid=["']([\w-]+)["'][\s\S]*?<\/section>/gi;
  while ((m = sectionRegex.exec(html)) !== null) {
    fragmentMatches.push({ id: m[1], html: m[0] });
  }
  const otherRegex = /<(div|main|dialog|header|footer)\b[^>]*\bid=["']([\w-]+)["'][\s\S]*?<\/\1>/gi;
  while ((m = otherRegex.exec(html)) !== null) {
    const id = m[2];
    if (!fragmentMatches.find(f => f.id === id)) fragmentMatches.push({ id, html: m[0] });
  }

  if (fragmentMatches.length === 0) {
    console.warn('No screen-like fragments found. Shell will still be created.');
  } else {
    for (const f of fragmentMatches) {
      const outPath = path.join(fragmentDir, `${f.id}.html`);
      await fs.writeFile(outPath, f.html, 'utf8');
      console.log('Wrote fragment:', path.relative(root, outPath));
      // remove the fragment from original html so it doesn't persist in shell
      html = html.replace(f.html, `<!-- fragment ${f.id} extracted -->`);
    }
  }

  // Write styles to src/styles.css
  const srcDir = path.join(root, 'src');
  await ensureDir(srcDir);
  const stylesPath = path.join(srcDir, 'styles.css');
  if (styles.trim()) {
    await fs.writeFile(stylesPath, `/* extracted from index.html */\n${styles}`, 'utf8');
    console.log('Wrote styles ->', path.relative(root, stylesPath));
    // remove original <style> blocks from html
    html = html.replace(styleRegex, '<!-- style extracted -->');
  } else {
    console.log('No inline <style> blocks found.');
  }

  // Build src/app.js
  const appJsPath = path.join(srcDir, 'app.js');

  // Safely embed extracted inline scripts using JSON.stringify to avoid escaping issues
  const safeAppScripts = JSON.stringify(appScripts);

  const appJsContent = `// Minimal fragment loader generated by tools/split-index.js
const ROOT = document.getElementById('app-root');

async function fetchFragment(path) {
  try {
    const res = await fetch(path, { cache: 'no-store' });
    if (!res.ok) throw new Error('Failed to fetch ' + path);
    return await res.text();
  } catch (e) {
    console.warn('Fragment fetch failed for', path, e);
    try {
      const r2 = await fetch('/offline.html', { cache: 'no-store' });
      if (r2.ok) return await r2.text();
    } catch (_) {}
    return '<div style="padding:20px;text-align:center">Unable to load content.</div>';
  }
}

function runInlineScripts(container, htmlString) {
  // extract scripts and run them in order
  const scriptRegex = /<script\\b([^>]*)>([\\s\\S]*?)<\\/script>/gi;
  const scripts = [];
  const cleaned = htmlString.replace(scriptRegex, (m, attr, code) => {
    scripts.push({ attr, code });
    return '';
  });
  container.innerHTML = cleaned;
  for (const s of scripts) {
    const el = document.createElement('script');
    const srcMatch = s.attr && s.attr.match(/src=[\\"']([^\\\\"']+)[\\"']/);
    if (srcMatch) {
      el.src = srcMatch[1];
      el.async = false;
      document.body.appendChild(el);
    } else {
      el.textContent = s.code;
      document.body.appendChild(el);
    }
    el.parentNode && el.parentNode.removeChild(el);
  }
}

const routes = { '/': '/screens/home.html', '/detail': '/screens/detail.html', '/create': '/screens/create.html' };

async function navigate(pathname) {
  const normalized = pathname || '/';
  const frag = routes[normalized] || routes['/'];
  const html = await fetchFragment(frag);
  runInlineScripts(ROOT, html);
  window.scrollTo(0,0);
  if (window.__screenShown) {
    try { window.__screenShown(normalized); } catch (e) {}
  }
}

document.addEventListener('click', (e) => {
  const a = e.target.closest('a[data-nav]');
  if (!a) return;
  e.preventDefault();
  const href = a.getAttribute('href') || '/';
  history.pushState({}, '', href);
  navigate(href);
});

window.addEventListener('popstate', () => navigate(location.pathname));
window.addEventListener('load', () => navigate(location.pathname || '/'));

// --- extracted inline scripts from index.html follow ---
(function runExtractedInline() {
  const scripts = ${safeAppScripts};
  if (scripts && scripts.length) {
    try {
      const el = document.createElement('script');
      el.type = 'text/javascript';
      el.text = scripts;
      document.body.appendChild(el);
      // leave it appended so that functions/vars remain accessible
    } catch (e) {
      console.warn('Failed to run extracted inline scripts', e);
    }
  }
})();
`;

  await fs.writeFile(appJsPath, appJsContent, 'utf8');
  console.log('Wrote app loader ->', path.relative(root, appJsPath));

  // Rebuild index.html shell: preserve head contents minimally
  const headMatch = html.match(/<head[^>]*>([\s\S]*?)<\/head>/i);
  let headInner = headMatch ? headMatch[1] : '';
  // strip any remaining inline style/script markers left in headInner
  headInner = headInner.replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi, '');
  headInner = headInner.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi, '');
  headInner = headInner.replace(/<!-- fragment [\w-]+ extracted -->/g, '');

  const newHead = `<head>
  ${headInner}
  <link rel="stylesheet" href="/src/styles.css">
  <title>${title}</title>
</head>`;

  const newBody = `<body>
  <div id="app-root" aria-live="polite"></div>
  <noscript><div style="padding:20px;text-align:center">JavaScript is required for EventCata.</div></noscript>
  ${externalScripts.map(s => `<script src="${s}"></script>`).join('\n  ')}
  <script type="module" src="/src/app.js"></script>
  <script>
    if ('serviceWorker' in navigator) {
      navigator.serviceWorker.register('/sw.js').catch(()=>{/*sw reg failed*/});
    }
  </script>
</body>`;

  const newHtml = '<!doctype html>\n<html lang="en">\n' + newHead + '\n' + newBody + '\n</html>';
  await fs.writeFile(idxPath, newHtml, 'utf8');
  console.log('Rewrote index.html as shell (original backed up).');

  console.log('\nDone. Inspect /screens, /src/styles.css, /src/app.js and test the app.');
}

run().catch(err => {
  console.error(err);
  process.exit(1);
});
