// Generated by tools/extract-shell.js — do not hand-edit; re-run the tool.
const ROOT = document.getElementById('app-root');

async function fetchFragment(url) {
  const res = await fetch(url, { cache: 'no-store' });
  if (!res.ok) throw new Error('Failed to fetch ' + url);
  return await res.text();
}

let shellReadyPromise = null;

function loadShellDom() {
  return fetchFragment('/screens/body-content.html').then((html) => {
    ROOT.innerHTML = html;
  });
}

function loadCatalog() {
  if (window.__eventcataCatalogLoaded) {
    return window.__eventcataCatalogScript || Promise.resolve();
  }
  window.__eventcataCatalogLoaded = true;
  window.__eventcataCatalogScript = new Promise((resolve, reject) => {
    const el = document.createElement('script');
    el.src = '/src/catalog.js?v=11';
    el.async = false;
    el.onload = () => resolve();
    el.onerror = () => reject(new Error('Failed to load catalog.js'));
    document.body.appendChild(el);
  });
  return window.__eventcataCatalogScript;
}

function ensureShell() {
  if (!shellReadyPromise) {
    shellReadyPromise = loadShellDom()
      .catch((e) => {
        console.warn('Shell fetch failed', e);
        return fetchFragment('/offline.html').then((h) => {
          ROOT.innerHTML = h;
        });
      })
      .then(() => loadCatalog())
      .catch((e) => {
        console.warn('Catalog load failed', e);
      });
  }
  return shellReadyPromise;
}

function pathToScreenId(pathname) {
  const p = pathname || '/';
  if (p === '/detail' || p === '/detail/') return 'detail';
  if (p === '/create' || p === '/create/') return 'create-screen';
  return 'home';
}

function applyPathToUi(pathname) {
  const path = pathname || '/';
  const params = new URLSearchParams(window.location.search);
  try {
    const eventMatch = path.match(/^\/e\/([^/]+)\/?$/);
    if (eventMatch && typeof window.openDetail === 'function') {
      window.openDetail(decodeURIComponent(eventMatch[1]));
      return;
    }
    if (path === '/detail' || path.startsWith('/detail')) {
      const eventId = params.get('id');
      if (eventId && typeof window.openDetail === 'function') {
        window.openDetail(eventId);
        return;
      }
      if (typeof window.navigate === 'function') window.navigate('home');
      return;
    }
    if ((path === '/create' || path === '/create/') && typeof window.openCreate === 'function') {
      window.openCreate();
      return;
    }
    const id = pathToScreenId(path);
    if (typeof window.navigate === 'function') window.navigate(id);
  } catch (e) {
    console.warn('applyPathToUi', e);
  }
}

async function navigatePath(pathname) {
  await ensureShell();
  applyPathToUi(pathname);
  window.scrollTo(0, 0);
  if (window.__screenShown) {
    try {
      window.__screenShown(pathname || '/');
    } catch (e) {}
  }
}

document.addEventListener('click', (e) => {
  const a = e.target.closest('a[data-nav]');
  if (!a) return;
  e.preventDefault();
  const href = a.getAttribute('href') || '/';
  history.pushState({}, '', href);
  void navigatePath(href);
});

window.addEventListener('popstate', () => {
  void navigatePath(location.pathname);
});

window.addEventListener('load', () => {
  void navigatePath(location.pathname || '/');
});
